### ISSUE TITLE
v2: Few-shot tasks don't have splits

### ISSUE THREAD

**Issue by TheExGenesis** [google-research/FLAN#17] opened 2023-02-20 13:33 UTC
Running `seqio.get_mixture_or_task("cot_fsopt").splits`

Errors `ValueError: Task cot_creak_template_0to10_x_shot has no splits`

**Comment by mansoor-s** [comment] 2023-02-20 20:52
I ran into a bunch of issues that I was able to bypass, but I'm currently blocked by the same error for a different task:
 `t0_task_adaptation:adversarial_qa_dbert_answer_the_following_q_template_0to10_no_opt_x_shot`


This is the printed error in the stack trace:

`KeyError: "Trying to access `splits['train']` but `splits` is empty. This likely indicate the dataset has not been generated yet."`

**Comment by jayelm** [comment] 2023-02-21 22:23
I was able to bypass this error by replacing `L266` of `seqio/seqio/experimental.py` (https://github.com/google/seqio/blob/main/seqio/experimental.py#L266) from

```
            num_shards = len(self._original_source.list_shards(split_))
```

to

```
            try:
                num_shards = len(self._original_source.list_shards(split_))
            except KeyError:
                self._original_source.tfds_dataset.builder.download_and_prepare()
                num_shards = len(self._original_source.list_shards(split_))
```

it seems like the download_and_prepare command is required to get the dataset downloaded (through huggingface). However it takes a really long time to download everything. Honestly feels like we're just doing alchemy at this point—probably best to wait till the authors clear things up.

**Comment by gauravmishra** [comment] 2023-02-24 02:08
Hi all, thanks for reporting and apologies for the inconvenience! I'm looking into this. I was able to repro the issue with the "t0_task_adaptation:adversarial_qa_dbert_answer_the_following_q_template_0to10_no_opt_x_shot" Task. I tried loading the underlying source dataset from TFDS ("huggingface:bigscience__p3/adversarial_qa_dbert_answer_the_following_q") and that failed; I'm investigating further.

I couldn't reproduce the error with the "cot_creak_template_0to10_x_shot" Task. @TheExGenesis could you provide the steps to repro this error?

**Comment by TheExGenesis** [comment] 2023-02-24 23:33
> Hi all, thanks for reporting and apologies for the inconvenience! I'm looking into this. I was able to repro the issue with the "t0_task_adaptation:adversarial_qa_dbert_answer_the_following_q_template_0to10_no_opt_x_shot" Task. I tried loading the underlying source dataset from TFDS ("huggingface:bigscience__p3/adversarial_qa_dbert_answer_the_following_q") and that failed; I'm investigating further.
> 
> I couldn't reproduce the error with the "cot_creak_template_0to10_x_shot" Task. @TheExGenesis could you provide the steps to repro this error?

Ignore mine, I can't reproduce it, but the T0 tasks all have this problem

**Comment by gahdritz** [comment] 2023-02-27 23:53
I'm having the same issue with the T0 tasks. TFDS doesn't recognize the provided dataset names.

**Comment by gahdritz** [comment] 2023-02-28 00:40
@mansoor-s @gauravmishra @TheExGenesis were you able to fix it?

**Comment by gauravmishra** [comment] 2023-02-28 21:10
I've reported the error to the TFDS folks and will post an update as soon as I hear back. It looks like the underlying TFDS dataset is broken, e.g. running the following on Colab:

!pip install datasets
!pip install tensorflow_datasets
import tensorflow_datasets as tfds
ds = tfds.load("huggingface:bigscience__p3/adversarial_qa_dbert_answer_the_following_q", split="train")

Gives me this error:
ValueError: 'full' is not a valid VerificationMode

**Comment by TheExGenesis** [comment] 2023-03-01 11:04
> I've reported the error to the TFDS folks and will post an update as soon as I hear back. It looks like the underlying TFDS dataset is broken, e.g. running the following on Colab:
> 
> !pip install datasets !pip install tensorflow_datasets import tensorflow_datasets as tfds ds = tfds.load("huggingface:bigscience__p3/adversarial_qa_dbert_answer_the_following_q", split="train")
> 
> Gives me this error: ValueError: 'full' is not a valid VerificationMode

yup, the latest nightly fixes this

**Comment by shayne-longpre** [comment] 2023-03-08 20:50
Looks like this was fixed? Will close if so.

**Comment by lehougoogle** [comment] 2023-03-08 20:58
Closing this issue for now. Plz re-open if needed.

**Closed by lehougoogle** 2023-03-08 20:58 UTC

**Comment by takiholadi** [comment] 2023-05-24 19:30
same problem with newest tfds-nightly and seqio-nightly
