### ISSUE TITLE
ERROR:absl:Failed to load task 'arc_challenge_template_0to10_no_opt_x_shot' as part of mixture 'flan2022_submix'

### ISSUE THREAD

**Issue by sxthunder** [google-research/FLAN#37] opened 2023-03-13 13:52 UTC
Using the latest commit, when I run python flan/v2/run_example.py, get the following error:

```
ERROR:absl:Failed to load task 'arc_challenge_template_0to10_no_opt_x_shot' as part of mixture 'flan2022_submix'
--------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[3], line 3
      1 INPUT_SEQ_LEN = 2056
      2 TARGET_SEQ_LEN = 512
----> 3 dataset = selected_mixture.get_dataset(
      4     sequence_length={"inputs": INPUT_SEQ_LEN, "targets": TARGET_SEQ_LEN},
      5     num_epochs=1,
      6     shuffle=True,
      7     copy_pretokenized=True,
      8     # The passthrough features let you track the source[/task/template](https://vscode-remote+ssh-002dremote-002b77.vscode-resource.vscode-cdn.net/task/template) metadata for the example
      9     passthrough_features=["_template_idx", "_task_source", "_task_name", "_template", "_template_type"]
     10 )

File [~/miniconda3/envs/flanv2/lib/python3.8/site-packages/seqio/dataset_providers.py:1730](https://vscode-remote+ssh-002dremote-002b77.vscode-resource.vscode-cdn.net/data/lm/project/instruction_dataset/FLAN/flan/v2/~/miniconda3/envs/flanv2/lib/python3.8/site-packages/seqio/dataset_providers.py:1730), in Mixture.get_dataset(self, sequence_length, split, use_cached, shuffle, seed, shard_info, num_epochs, copy_pretokenized, compute_stats_empirically, log_mixing_proportions, passthrough_features, trim_output_features)
   1728 for task in tasks:
   1729   try:
-> 1730     ds = task.get_dataset(
   1731         sequence_length,
   1732         split=split,
   1733         use_cached=use_cached,
   1734         shuffle=shuffle,
   1735         seed=seed,
   1736         shard_info=shard_info,
   1737         num_epochs=num_epochs,
...
    394     )
    395   # 1st case: The key exists: info.splits['train']
    396   elif str(key) in self.keys():

KeyError: "Trying to access splits['train[:-200]'] but splits is empty. This likely indicate the dataset has not been generated yet."```

**Comment by shayne-longpre** [comment] 2023-03-13 15:34
I haven't been able to reproduce this error. Have you tried starting from a new virtual environment and installing just the flan/v2/requirements.txt?

If you have the error and can share it in a colab notebook I can take a closer look.

**Comment by sxthunder** [comment] 2023-03-13 15:41
I solve this by manually using tf.load the missing dataset

**Comment by sxthunder** [comment] 2023-03-13 15:42
```
from task_configs import FLAN_V0_TASK_CONFIGS, DIALOG_TASK_CONFIGS, T0_TASK_CONFIGS, NIV2_TASK_CONFIGS

config_dict = {
    "flan": FLAN_V0_TASK_CONFIGS,
    "dialog": DIALOG_TASK_CONFIGS,
    "t0": T0_TASK_CONFIGS,
    "niv2": NIV2_TASK_CONFIGS
}

def main():
      for config_name, config in config_dict.items():
          print("#" *20 + "Downloading {}".format(config_name) + "#" * 20)

          for ds_name, ds_config in config.items():
              print("downloading {}...".format(ds_name))
              load = ds_config.source.get_dataset()

if __name__ == "__main__":
    main()```

**Comment by conceptofmind** [comment] 2023-03-14 22:33
I am having this issue as well

**Comment by shayne-longpre** [comment] 2023-03-16 15:57
@conceptofmind could you provide this error in a colab? I am not able to reproduce it on my side. It could be an issue with the dependency versions or an error with downloading the datasets first from their original sources.

**Comment by conceptofmind** [comment] 2023-03-16 16:00
> @conceptofmind could you provide this error in a colab? I am not able to reproduce it on my side. It could be an issue with the dependency versions or an error with downloading the datasets first from their original sources.

I believe that it is an issue with downloading the datasets. Some of the checksums have changed and it causes tfds to also throw an error and halt downloading. I will manually download the missing datasets and see if it works from there.

**Comment by shayne-longpre** [comment] 2023-03-22 14:16
@sxthunder @conceptofmind  I'm still waiting to hear back from TFDS. My Google colleagues think the issue is on their end. In the meantime, would either of you be willing to share the code you used to circumvent it? That would be greatly appreciated, so I can suggest the same to other people working on this. Thank you!

**Comment by sxthunder** [comment] 2023-03-22 14:21
> ```
> from task_configs import FLAN_V0_TASK_CONFIGS, DIALOG_TASK_CONFIGS, T0_TASK_CONFIGS, NIV2_TASK_CONFIGS
> 
> config_dict = {
>     "flan": FLAN_V0_TASK_CONFIGS,
>     "dialog": DIALOG_TASK_CONFIGS,
>     "t0": T0_TASK_CONFIGS,
>     "niv2": NIV2_TASK_CONFIGS
> }
> 
> def main():
>       for config_name, config in config_dict.items():
>           print("#" *20 + "Downloading {}".format(config_name) + "#" * 20)
> 
>           for ds_name, ds_config in config.items():
>               print("downloading {}...".format(ds_name))
>               load = ds_config.source.get_dataset()
> 
> if __name__ == "__main__":
>     main()```
> ```

I have tried this function, but the download process is to long... Can you directly offer the processed dataset? maybe it is more convenient for people to use. Just like OIG dataset https://huggingface.co/datasets/laion/OIG. And I also see OIG-40M contains flan v2, but only have 100W samples

**Comment by conceptofmind** [comment] 2023-03-22 17:55
@shayne-longpre The download link for Newsroom also seems to not work for me.

**Comment by AadSah** [comment] 2023-03-29 20:26
Hi @conceptofmind, were you able to find any workarounds for the above issues?

**Comment by AadSah** [comment] 2023-03-29 21:08
@conceptofmind Thanks for the reply, how did you fix the cloze data issue? Also, for the `dialog` tasks, did you face any issues with Apache Beam? And for processing all the tasks did you follow this repo: https://huggingface.co/datasets/SirNeural/flan_v2?

Also, it would be of great help if you can make the processed files public, something like the above repo!

**Comment by conceptofmind** [comment] 2023-03-29 21:14
> @conceptofmind Thanks for the reply, how did you fix the cloze data issue? Also, for the `dialog` tasks, did you face any issues with Apache Beam? And for processing all the tasks did you follow this repo: https://huggingface.co/datasets/SirNeural/flan_v2?
> 
> Also, it would be of great help if you can make the processed files public, something like the above repo!

I obtained the Clozee data from a peer who had previously downloaded a copy. I did not have any issues with Apache beam. Wiki dialog downloaded after many hours. I had seen that script from Sir Neural but it does not work and causes many issues with encoding and decoding. I used my own script which is a combination of his and `run_example.py`.

All of the processed files will be open-sourced on Huggingface in the near future: https://huggingface.co/datasets/conceptofmind/flan_dialog_submix

Access to the files is limited to Stability AI researchers until we finish training models and writing a short paper as suggested by Yi Tay.

**Comment by AadSah** [comment] 2023-03-29 21:18
Great, thanks a lot! Looking forward to the open-sourcing of the processed files! In the meantime would it be possible to make the script public maybe?

**Comment by conceptofmind** [comment] 2023-03-29 21:21
> Great, thanks a lot! Looking forward to the open-sourcing of the processed files! In the meantime would it be possible to make the script public maybe?

When I finish uploading everything and get it cleaned up, sure.

**Comment by shayne-longpre** [comment] 2023-03-30 19:25
@conceptofmind Thank you for these updates. What is the issue with CosmosQA? Do you mean the TFDS one [here](https://www.tensorflow.org/datasets/catalog/cosmos_qa) -- is it something I should post an issue for?

And other than that, is it just the fix to NIv2 Few-Shot left that you need?

**Comment by conceptofmind** [comment] 2023-03-31 04:25
> @conceptofmind Thank you for these updates. What is the issue with CosmosQA? Do you mean the TFDS one [here](https://www.tensorflow.org/datasets/catalog/cosmos_qa) -- is it something I should post an issue for?
> 
> And other than that, is it just the fix to NIv2 Few-Shot left that you need?

I am not sure why I am getting a `key` error when trying to build the CosmosQA dataset. I am referring to the tfds one. I have already opened an issue [here](https://github.com/tensorflow/datasets/issues/4817). I have a peer currently working on building the t0 dataset. I will see if he can build CosmosQA without issue.

After that, the only remaining dataset is Niv2 Few-shot.

Thank you,

Enrico

**Comment by shayne-longpre** [comment] 2023-04-11 02:57
@AadSah The NIv2 few-shot has been fixed in the recent PRs

**Closed by shayne-longpre** 2023-04-11 02:57 UTC
