### ISSUE TITLE
There may be some bugs in data preprocessing

### ISSUE THREAD

**Issue by choosewhatulike** [google-research/FLAN#25] opened 2023-03-03 01:27 UTC
Thank you for sharing the templates and data. It is really helpful! 

I am trying to reproduce the data collection but found that some task splits may be wrong preprocessed in T0. The targets of some tasks with no_opt templates are not correct.

There are some examples, comparing the `_no_opt_zero_shot` with the `_zero shot`:
```
t0_task_adaptation:sciq_Direct_Question_Closed_Book__template_0to10_zero_shot
{'input': 'Q: Where are most of the organs contained in insects?   A:\nAvailable options: (a). head. (b). appendages. (c). thorax. (d). the abdomen.', 'target': '(d).'}                                                                                                                 
t0_task_adaptation:sciq_Direct_Question_Closed_Book__template_0to10_no_opt_zero_shot
{'input': 'Q: Where are most of the organs contained in insects?   A:', 'target': '[4].'} 

t0_task_adaptation:social_i_qa_I_was_wondering_template_0to10_zero_shot
{'input': "I heard that Alex gave Lee's son a toy to keep him busy during the movie.  And I was wondering What will happen to Lee?\nPossible answers: [-] make a movie; [-] be liked by Lee's son; [-] thank Alex;", 'target': 'thank Alex'}
t0_task_adaptation:social_i_qa_I_was_wondering_template_0to10_no_opt_zero_shot
{'input': "I heard that Alex gave Lee's son a toy to keep him busy during the movie.  And I was wondering What will happen to Lee?", 'target': '(c).'}

t0_task_adaptation:qasc_is_correct_2_template_0to10_zero_shot
{'input': 'Do you think the right answer to the question "what is plasma created with?" is "urea", given that  plasma can be created with heat?\nChoose your answer from:\n(i). Yes.\n(ii). No.', 'target': '(i).'}
t0_task_adaptation:qasc_is_correct_2_template_0to10_no_opt_zero_shot
{'input': 'Do you think the right answer to the question "what is plasma created with?" is "urea", given that  plasma can be created with heat?', 'target': '1).'}
```

Does the bug come from the original T0 collection or from the code of preprocessing?  I have no clue about this. As I found most tasks in T0 are correct, and only a few have such wrong targets.

**Comment by choosewhatulike** [comment] 2023-03-03 01:44
And there is a bug in the preprocessing of niv2 collection when building few shot examples. It seems like the demonstrates are sampled from the whole collection of niv2 instead of in the scope of the given task. This makes the demonstration examples from other unrelated tasks appear, which could be noise and distract the model when training.

Some examples here:
```
tfds_natural_instructions_template_0to10_x_shot
{"input": "In this task, you are given two phrases: Head and Tail, separated with <sep>. The Head and the Tail events are short phrases possibly involving participants. The names of specific people have been replaced by generic words (e.g., PersonX, PersonY, PersonZ). PersonX is always the subject of the event. You have to determine whether, as a result of the Head, PersonX will be affected as mentioned in the Tail or not. These effects are social actions that may occur after the Head event. Classify your answers into \"Yes\" and \"No\". The phrase may also contain \"___\", a placeholder that can be an object, a person, and/or an action.\n\n[EX Q]: [80, 158, 111, 229, 227, 195, 281, 150, 81, 221, 88, 143, 190, 245, 54, 39, 57, 132, 52, 44] k=9\n[EX A]: [89, 167, 120, 238, 236, 204, 290, 159, 90, 230, 97, 152, 199, 254, 63, 48, 66, 141, 61, 53]\n\n[EX Q]: Vous êtes susceptible de battre un bateau dans le canot.\n[EX A]: Vous êtes susceptible de trouver un magasin dans l'application.\n\n[EX Q]: Head: PersonX bears ___ unto the PersonY<sep>Tail: his soul\n[EX A]:", "target": "No"}
{"input": "In this task, you need to generate an appropriate title for the given summary of some paragraph. The generated title must be short and should include the main topic of the given text. Your summary should be less than 20 words long.\n\nExample Input: Background Paragraph: Some mutations have a positive effect on the organism in which they occur. They are called beneficial mutations . They lead to new versions of proteins that help organisms adapt to changes in their environment. Beneficial mutations are essential for evolution to occur. They increase an organism’s changes of surviving or reproducing, so they are likely to become more common over time. There are several well-known examples of beneficial mutations. Here are just two:. \nStory: Organisms are constantly exposed to different kinds of radiations. Keith was studying the effect of radiations on a organism in two different locations, place A and place B. He noticed that in place A the the organism had beneficial mutation due to the radiation. On the other hand, in place B, the organism didn't have beneficial mutation. \nQuestion: In place A would the organism more likely or less likely develop proteins to adapt in their habitat than place B?\nExample Output: more likely.\n\nExample Input: Malik feels scared.\nExample Output: fear\n\nExample Input: Rihanna says that she she still loves ex-boyfriend Chris Brown despite him attacking her in 2009.\nExample Output:", "target": "Rihanna 'still loves' Chris Brown after assault"}
{"input": "In this task you are given a list of triplets of the form [subject, predicate, object] and the output should be a question based on the triplets but with the subject and/or object replaced with blanks (represented using two or more consecutive underscores). Triplet values encompassed in [*] are special tokens that can be replaced with synonyms. The objective is to construct a question in a manner that (a) captures the facts specified in at least one of the triplets, and (b) ideally contains a limited number of blanks such that it is a well-formed question that is easy to answer. A blank can represent a single word or a phrase.\n\nQ: Context Word: Pencil.\n\nA: PersonX gave his pen to PersonY because _ didn't need a pen, as the test required pencil.\n****\nQ: تشعرون بالارتياح ؟\n\nA: ¿Satisfechos?\n****\nQ: [['Cotto', 'eatType', 'coffee shop'], ['Cotto', 'priceRange', 'moderate'], ['Cotto', 'customer rating', '3 out of 5'], ['Cotto', 'area', 'city centre'], ['Cotto', 'near', 'The Portland Arms']]\n\nA:", "target": "Situated near The Portland Arms on the riverfront, north of the City centre, the 3-star '_____' coffee shop serves a range of moderately-priced fast foods.\n****"}
```

**Comment by lehougoogle** [comment] 2023-03-03 15:27
Thanks for catching this!
I believe the reason is that at some point, we changed NIv2 from a collection of tasks to a single task. The few_shot examples are randomly sampled from the same task. We'll figure out potential fixes.

**Comment by shayne-longpre** [comment] 2023-03-11 01:31
@choosewhatulike The T0 issue should be fixed by https://github.com/google-research/FLAN/pull/30.

The fix to Natural Instructions is a little more complicated, and on its way.

**Comment by choosewhatulike** [comment] 2023-03-11 05:42
Thanks a lot for your reply and the quick fix!

**Comment by conceptofmind** [comment] 2023-03-14 20:09
> @choosewhatulike The T0 issue should be fixed by #30.
> 
> The fix to Natural Instructions is a little more complicated, and on its way.

Hello,

Just to confirm. I should be processing all of the mixtures except for Natural Instructions?

Thank you,

Enrico

**Comment by shayne-longpre** [comment] 2023-03-14 20:24
@conceptofmind Yes, or specifically all the mixtures in the `flan/v2/run_examples.py` file except for the Natural Instructions submixture.

**Comment by conceptofmind** [comment] 2023-03-14 20:31
> @conceptofmind Yes, or specifically all the mixtures in the `flan/v2/run_examples.py` file except for the Natural Instructions submixture.

Ok. Thank you. Natural Instructions take up a decent portion of the flan v2 2022 mixture. Would you recommend waiting on the fix to be patched before generating the dataset?

**Comment by TheExGenesis** [comment] 2023-03-20 18:33
I guess you can use only the zero-shot versions of natural instructions? Those shouldn't be affected by the problems of few-shot example generation.

**Comment by shayne-longpre** [comment] 2023-03-20 19:17
@conceptofmind sorry I missed this. You can simply generate the`"t0_submix"` submixture by itself, and combine it with any other mixtures later with a rate of your choice. The mixture rates are normalized with respect to the other rates, so doing what you suggested above would be no different from `('t0_submix', 1)`.

@TheExGenesis  is correct, NIv2 Zero-shot is correct. It is on my TODO list to integrate the fix to NIv2 Few-Shot: https://github.com/google-research/FLAN/pull/43.

**Comment by conceptofmind** [comment] 2023-03-22 16:01
> @conceptofmind sorry I missed this. You can simply generate the`"t0_submix"` submixture by itself, and combine it with any other mixtures later with a rate of your choice. The mixture rates are normalized with respect to the other rates, so doing what you suggested above would be no different from `('t0_submix', 1)`.
> 
> @TheExGenesis is correct, NIv2 Zero-shot is correct. It is on my TODO list to integrate the fix to NIv2 Few-Shot: #43.

Thank you for the update. I will keep this in mind when creating the submixes.

**Comment by jianguoz** [comment] 2023-03-23 21:39
Hi @shayne-longpre, Since due to the data are too large, we cannot directly run the below example, and instead we need to run them one by one. To calculate examples for each submix like `flan2021_submix`. 
Can I know that will seqio randomly samples 40% data from the whole 'flan2021_submix', or it will randomly samples 40% data for each task or each zsopt, zsnopt, fsopt, and fsnoopt s separately in 'flan2021_submix' and then merge them together? Thanks:)
```
seqio.MixtureRegistry.add(
    'flan2022_submix',
        ('flan2021_submix', 0.4),  # mixing weight = 40%
        ('t0_submix', 0.32),       # mixing weight = 32%
        ('niv2_submix', 0.2),      # mixing weight = 20%
        ('cot_submix', 0.05),      # mixing weight = 5%
        ('dialog_submix', 0.03),   # mixing weight = 3%
```

**Comment by shayne-longpre** [comment] 2023-03-24 16:06
@jianguoz The way to think about this is not in terms of number of examples, but how long you want to train for. When you ask Seqio for 1 epoch of data from this mixture, it will keep generating examples, sampling according to the mixing rates, until *any one of the datasets has depleted all its examples*. (CC @adarob to confirm this.)

This means that very large datasets with a low relative mixing rate (e.g. Wiki Dialog, with 10M+ examples) will not make it through all its examples in 1 Seqio epoch. A second Seqio epoch will randomly sample from all the tasks again, potentially selecting different examples from Wiki Dialog, but again not all of them, in order to satisfy the mixing rates. I'm not sure how many examples this will turn out to be exactly, but we would recommend to continue sampling until your learning curve converges.

I'm not sure I follow your first question, as to whether to sample 40% of `flan2021_submix` or each of its constituent sub-submixtures (`flan_zsopt`, `flan_zsnoopt`, `flan_fsopt`, `flan_fsnoopt`). Basically seqio multiplies the rates at each sub-mixture level of hierarchy, so 0.4 * 0.25 = 0.1 is the final rate for each of (`flan_zsopt`, `flan_zsnoopt`, `flan_fsopt`, `flan_fsnoopt`) since they each had the same rate (1,1,1,1). So you could generate each sub-submixture separately and compute how much to sample from each in the final mix, and that would be fine too.

I hope this answers your question! If not, feel free to ask more and I will clarify further with examples.

**Comment by jianguoz** [comment] 2023-03-24 17:15
Hi @shayne-longpre , thanks very much for your reply and examples! Regarding `0.4 * 0.25 = 0.1 is the final rate for each of (flan_zsopt, flan_zsnoopt, flan_fsopt, flan_fsnoopt)`, I did a check and found that some tasks in each split only have a few examples, while other tasks have a large amount of data and maybe ten times large than other tasks. In your experience, is it better to apply some techniques such as `example-proportional sampling (EPS)` . Another way is that we can consider another way, i.e., for each submixture `(flan_zsopt, flan_zsnoopt, flan_fsopt, flan_fsnoopt)` in the  `flan2021_submix`, we first group examples by each task, and then we do equal sampling for each task, as such we can balance the examples for each task. Could you give some experiences or comments here? Thanks:)

**Comment by shayne-longpre** [comment] 2023-03-24 19:52
@jianguoz Glad to help! And great question. I think these approaches are very reasonable and could even offer improvements as we did not have time to explore sampling techniques at this level of granularity. 

Intuitively I would suspect the best approaches slightly over-sample harder tasks (e.g. commonsense reasoning over sentiment analysis), but ensure the model sees as diverse examples as possible (so ensuring no tasks/datasets are almost completely ignored). This is especially true if you want a model with as broad of capabilities as possible. However, if you care about a small subset of task types or domains then, intuitively, sample higher from those.

**Comment by jianguoz** [comment] 2023-03-24 20:53
Hi @shayne-longpre, thanks very much for your great suggestions! One side thing is that I notice that you removed MMLU tasks `range(685, 738)` in NIV2 (https://github.com/google-research/FLAN/blob/main/flan/v2/task_configs.py#L221). However, I found that `task664 to task667`  in NIV2 (https://github.com/google-research/FLAN/blob/main/flan/v2/constants_niv2.py#L11963) are also MMLU tasks, which are not removed by the code. Maybe we should update that part of code. Can I also know that whether the open-sourced Huggingface FlanT5 checkpoint have  removed `task664 to task667` or not? Thanks

**Comment by shayne-longpre** [comment] 2023-03-24 21:14
@jianguoz thanks for catching this! I can confirm that originally (internally) we filtered those out, using the "mmmlu" string in the NIv2 task names. It looks like during migration to external they changed it for some reason and missed those two. I will submit a change soon.

Thanks!

**Comment by conceptofmind** [comment] 2023-03-25 01:56
@jianguoz @shayne-longpre Going to be uploading all of the submixes and tasks to Huggingface as they process: https://huggingface.co/datasets/conceptofmind/flan_niv2_zsopt

Still need to fix issues with tfds not downloading datasets but I will upload what I can in the meantime.

**Comment by shayne-longpre** [comment] 2023-03-25 19:58
@conceptofmind Thanks for doing this! Can I ask what stop condition are you using? Is it 1 Seqio epoch of each, so that each of the atomic tasks are sampled equally?

**Comment by conceptofmind** [comment] 2023-03-25 20:04
> 

This is what I am doing for single tasks:
```python
def process_example(ex):
    output = json.dumps({
            "inputs": ex["inputs_pretokenized"].decode(),
            "targets": ex["targets_pretokenized"].decode(),
            "task_source": ex["_task_source"].decode(),
            "task_name": ex["_task_name"].decode(),
        })
    return output

if __name__ == "__main__":
    selected_mixture = seqio.get_mixture_or_task('dialog_fsopt')

    dataset = selected_mixture.get_dataset(
        sequence_length={"inputs": 4096, "targets": 4096},
        split="train",
        num_epochs=1,
        shuffle=True,
        copy_pretokenized=True,
        passthrough_features=["_task_source", "_task_name"]
    )

    with Pool(48) as pool:

        # write out the data to a new json line file
        with open("dialog_fsopt.jsonl", "w") as f:
            for json_ex in tqdm.tqdm(pool.imap_unordered(process_example, dataset.as_numpy_iterator())):
                f.write(json_ex)
                f.write("\n")

    pool.close()
    pool.join()
```
Or if I want to build the submix:
```python
seqio.MixtureRegistry.add(
    'dialog_submix',
    tasks=[
        ('dialog_zsopt', 1),    # mixing weight = 50%
        ('dialog_fsopt', 1),    # mixing weight = 50%
    ])
```
```python
selected_mixture = seqio.get_mixture_or_task('dialog_submix')
```
Let me know if this looks alright to you.

Thank you,

Enrico

**Comment by shayne-longpre** [comment] 2023-03-25 20:43
@conceptofmind Thank you for sharing Enrico, I think this looks good! 

I'm curious if you see any issues with multilingual tasks in niv2 like #29 with this decoding?

**Comment by conceptofmind** [comment] 2023-03-25 20:57
> @conceptofmind Thank you for sharing Enrico, I think this looks good!
> 
> I'm curious if you see any issues with multilingual tasks in niv2 like #29 with this decoding?

I did not seem to have that issue with multilingual tasks. For example:
```
"Given the task definition and input, reply with output. You are given a sentence in Italian. Your job is to translate the Italian sentence into Farsi. Vi consiglio Jim Wallace e Tony Campolo. " "من جیم والس و تونی کمپولو را توصیه می کنم."
```
```
"Instructions: A text is given in Hindi. Translate it from the Hindi language to the Marathi language. The translation must not omit or add information to the original sentence. Input: वस्तूंवरील दरात बदल आणि स्पष्टीकरणासंदर्भात जीएसटी परिषदेच्या ३१ व्या बैठकीत करण्यात आलेल्या शिफारशी Output:" "दर परिवर्तन और वस्तुओं में स्पष्टता को लेकर हुई जीएसटी परिषद् की 31वीं बैठक में फैसले किए गए"
```
I think the problem was how they encoded and then decoded again. The dataset uploaded to and promoted by Huggingface was in a pretty abysmal state. Multiple improperly tokenized sequences and broken files. **I hope that did not occur this time lol.** I will need to have people review the datasets I am uploading.

Also, I can not progress with some datasets because I am unable to build them for some reason. Such as comos qa. I opened an issue. Someone could potentially give me their downloaded files and that may resolve this.

Thank you,

Enrico

**Comment by conceptofmind** [comment] 2023-03-28 02:27
I have found a few rare examples where there is improper tokenization due to I would imagine the T5 tokenizer:
```
"What was likely said next? CONVERSATION:Conversation: --What is Mirz ⁇ m ⁇ mm ⁇ dq ⁇ şlaq? --Mirzəməmmədqışlaq Mirzəməmmədqışlaq (also, Mirzamamedkyshlak and Mirzamamedkyshlakh) is a village in the Khachmaz Rayon of Azerbaijan. --Is it a city in Azerbaijan? --" | "The village forms part of the municipality of Qımılqışlaq."
-- | --
```
I will have to do additional preprocessing on these.

**Comment by shayne-longpre** [comment] 2023-03-30 19:47
@conceptofmind Thank you for the updates! Unfortunately I don't think I have the downloaded CosmosQA, but let me know if I can help push on the issue you created.

Interesting that you found a couple rare encoding issues. If you see what causes it or how to remedy it I am happy to push a fix. But the original Flan-T5 models were likely trained with these examples.

**Comment by conceptofmind** [comment] 2023-03-31 04:21
> @conceptofmind Thank you for the updates! Unfortunately I don't think I have the downloaded CosmosQA, but let me know if I can help push on the issue you created.
> 
> Interesting that you found a couple rare encoding issues. If you see what causes it or how to remedy it I am happy to push a fix. But the original Flan-T5 models were likely trained with these examples.

A peer and I were discussing what might be causing some of the rare encoding issues. He believed that it was because `utf8` was not specified and that in cases where the encoding fails, it is due to the system defaulting back to ASCII. We are still investigating this further. We plan to clean all examples regardless. Are there any major improvements that you think should be included? Yi Tay had suggested writing a paper on releasing a new FLAN dataset.

**Comment by jianguoz** [comment] 2023-04-07 18:16
Hi @conceptofmind, thanks for sharing the data in huggingface! However, we found that we need to submit requests to access your processed data, and some of the requests were submitted more than 1 week ago and no responses so far. Do you consider to release the access to general download? Thanks:)

**Comment by conceptofmind** [comment] 2023-04-07 19:41
> Hi @conceptofmind, thanks for sharing the data in huggingface! However, we found that we need to submit requests to access your processed data, and some of the requests were submitted more than 1 week ago and no responses so far. Do you consider to release the access to general download? Thanks:)

Hi @jianguoz ,

I am going to be open-sourcing all of the data. I am uploading cleaned and deduplicated versions as well. Currently, the datasets are reserved for StabilityAI researchers and associated groups until we finish training our models. We will release the datasets and paper hopefully in the very near future.

Best,

Enrico

**Comment by jianguoz** [comment] 2023-04-07 20:53
Hi @conceptofmind Thank you so much and look forward to your new release!

**Comment by shayne-longpre** [comment] 2023-04-11 02:52
@choosewhatulike Your original reported issues should be fixed. We just merged the fix for NIv2 few-shot and the T0 was fixed a while ago. Thank you for your patience!

**Comment by choosewhatulike** [comment] 2023-04-11 06:46
> @choosewhatulike Your original reported issues should be fixed. We just merged the fix for NIv2 few-shot and the T0 was fixed a while ago. Thank you for your patience!

@shayne-longpre Hi, Thanks a lot for your reply and the fix! This is really helpful.

**Closed** 2023-04-15 15:43 UTC
